In [53]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [54]:
data_set = load_iris()
X_independent_variables = data_set.data[0:100, :]
y_dependent_variable = data_set.target[0:100]

print(f"Dimension of X: {X_independent_variables.shape}")
print(f"Dimension of y: {y_dependent_variable}")
print(f"X independent variables: \n{X_independent_variables}")
print(f"y dependent variable: \n{y_dependent_variable}")

Dimension of X: (100, 4)
Dimension of y: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
X independent variables: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3

<h1>Standardizing data</h1>

In [55]:
def standarize_data(X):
    mean = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_standarded = (X-mean)/sigma
    return X_standarded, mean, sigma

In [56]:
def split_data(X, y, percentage_train = 80.0):
    np.random.seed(100)
    number_of_all_datapoints = X.shape[0]
    number_of_train_datapoints = int(np.round(X.shape[0]*percentage_train/100))
    indices_train = np.random.choice(number_of_all_datapoints, number_of_train_datapoints, replace=False).tolist()
    indices_test = list(set(np.arange(X.shape[0]))-set(indices_train))
    
    X_train = X[indices_train, :]
    y_train = y[indices_train]
    X_test = X[indices_test, :]
    y_test = y[indices_test]
    
    return X_train, y_train, X_test, y_test

In [57]:
X_train, y_train, X_test, y_test = split_data(X_independent_variables, y_dependent_variable)

print(f"Dimension of X training data: {X_train.shape}")
print(f"Dimension of y training data: {y_train.shape}")

print(f"X training data: {X_train}")
print(f"y training data: {y_train}")
print(f"X test data: {X_test}")
print(f"y test data: {y_test}")

Dimension of X training data: (80, 4)
Dimension of y training data: (80,)
X training data: [[4.9 3.6 1.4 0.1]
 [6.  2.2 4.  1. ]
 [5.  3.4 1.6 0.4]
 [4.5 2.3 1.3 0.3]
 [5.  3.2 1.2 0.2]
 [5.  3.  1.6 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [6.7 3.  5.  1.7]
 [5.1 3.7 1.5 0.4]
 [6.  3.4 4.5 1.6]
 [7.  3.2 4.7 1.4]
 [5.8 2.6 4.  1.2]
 [5.6 2.5 3.9 1.1]
 [5.7 2.9 4.2 1.3]
 [6.  2.9 4.5 1.5]
 [6.3 2.5 4.9 1.5]
 [5.4 3.9 1.7 0.4]
 [5.  3.5 1.3 0.3]
 [4.8 3.4 1.6 0.2]
 [4.7 3.2 1.6 0.2]
 [6.  2.7 5.1 1.6]
 [5.8 2.7 3.9 1.2]
 [5.  3.5 1.6 0.6]
 [5.2 3.4 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [5.5 2.6 4.4 1.2]
 [6.7 3.1 4.7 1.5]
 [5.4 3.4 1.7 0.2]
 [5.2 4.1 1.5 0.1]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.8 3.  1.4 0.1]
 [6.4 3.2 4.5 1.5]
 [5.4 3.  4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [5.6 2.9 3.6 1.3]
 [6.5 2.8 4.6 1.5]
 [6.2 2.2 4.5 1.5]
 [6.6 3.  4.4 1.4]
 [6.4 2.9 4.3 1.3]
 [4.9 2.4 3.3 1. ]
 [4.4 3.2 1.3 0.2]
 [6.8 2.8 4.8 1.4]
 [5.7 2.8 4.1 1.3]
 [5.1 3.5 1.4 0.3]
 [5.  2.3 3.3 1.

In [58]:
X_train_standarded, _, _ = standarize_data(X_train)
X_test_standarded, mean_test, sigma_test = standarize_data(X_test)

print(f"Standarded X training data: {X_train_standarded}")
print(f"Standarded X testing data: {X_test_standarded}")

Standarded X training data: [[-0.89579773  1.15786408 -1.04172561 -1.25212374]
 [ 0.81418492 -2.05205614  0.74164004  0.32673632]
 [-0.74034476  0.69930405 -0.90454364 -0.72583705]
 [-1.5176096  -1.82277613 -1.1103166  -0.90126595]
 [-0.74034476  0.24074402 -1.17890759 -1.07669484]
 [-0.74034476 -0.21781602 -0.90454364 -1.07669484]
 [ 0.03692008  0.92858407 -1.1103166  -1.07669484]
 [ 0.03692008  2.53354418 -1.04172561 -1.07669484]
 [ 1.90235569 -0.21781602  1.42754991  1.55473858]
 [-0.58489179  1.3871441  -0.97313463 -0.72583705]
 [ 0.81418492  0.69930405  1.08459498  1.37930968]
 [ 2.36871459  0.24074402  1.22177695  1.02845189]
 [ 0.50327898 -1.13493608  0.74164004  0.67759411]
 [ 0.19237305 -1.3642161   0.67304906  0.50216521]
 [ 0.34782602 -0.44709603  0.87882202  0.853023  ]
 [ 0.81418492 -0.44709603  1.08459498  1.20388079]
 [ 1.28054382 -1.3642161   1.35895893  1.20388079]
 [-0.11853289  1.84570413 -0.83595265 -0.72583705]
 [-0.74034476  0.92858407 -1.1103166  -0.90126595]
 [-

<h1>Logistic Regression for classification</h1>
<h3 style="color: green">Hypothesis:</h3>

\begin{equation*}
    h_\theta(x) = g(\theta^Tx)
\end{equation*}

Hypothesis is a function, that maps our inputs and model's parameters to the output results. <b>It's our model!</b>

<h4>Sigmoid:</h4>

\begin{equation*}
    g(z) = \frac{1}{1+e^{-z}}
\end{equation*}

<img src='https://miro.medium.com/v2/resize:fit:1280/1*OUOB_YF41M-O4GgZH_F2rw.png' />

<h3 style="color: red">Cost function: </h3>

\begin{equation*}
	J(\theta) = \frac{1}{m} \sum_{i=1}^{m} [-y^{(i)}\log(h_\theta(x^{(i)})) - (1-y^{(i)})\log(1-h_\theta(x^{(i)}))]	
\end{equation*}

It's Binary Cross Entropy that will produce cost of our model!.
We must <b>minimize cost function</b> by changing the model's parameters (theta).

<h3 style="color: cyan">Optimization by using <b>Linear Gradient</b></h3>

\begin{equation*}
    \theta_n := \theta_n - \alpha \cdot \frac{\partial J(\theta)}{\partial \theta_n}
\end{equation*}